#!/bin/sh

echo "Running Checkstyle..."
./gradlew checkstyleMain

if [ $? -ne 0 ]; then
    echo "Checkstyle found violations, but the commit will proceed."
else
    echo "Checkstyle passed with no violations."
fi
